// Resources content — blog + glossary seed data for the marketing site.
// Kept separate from the app so writers can extend it without touching UI code.
// Body blocks: { h: "..." } heading · { p: "..." } paragraph · { ul: [...] } list.

export const BLOG_CATEGORIES = [
  { slug: "ai-hiring", label: "AI & Hiring", desc: "How AI is changing screening, matching and hiring decisions.", icon: "matching", tint: "#D98BF5" },
  { slug: "recruiting-ops", label: "Recruiting Ops", desc: "Process, pipelines and the systems behind great hiring.", icon: "settings", tint: "#A98CFF" },
  { slug: "interviewing", label: "Interviewing", desc: "Structured interviews, scorecards and fairer decisions.", icon: "interview", tint: "#7FA0FF" },
];

export const BLOG_POSTS = [
  {
    slug: "how-ai-resume-screening-works",
    title: "How AI resume screening actually works (and where it doesn't)",
    category: "ai-hiring",
    excerpt: "Parsing, matching and ranking explained in plain terms — plus the parts you should still do yourself.",
    author: { name: "Amira Hassan", role: "Head of Product" },
    date: "2026-06-24",
    readMins: 7,
    tags: ["AI screening", "Resume parsing", "Match scoring"],
    body: [
      { p: "\"AI screening\" gets used to mean everything from a keyword filter to a black-box score. The useful version is narrower and more honest: read each resume, turn it into structured data, compare it to the role, and put the strongest fits on top — with the reasons attached. Here's what each step really does." },
      { h: "1. Parsing: turning a PDF into data" },
      { p: "A resume is a document; a pipeline needs fields. Parsing extracts skills, titles, companies, dates and a short summary from whatever layout the candidate used. Good parsing is boring and reliable — it means no one is retyping a CV into a form, and every applicant is comparable on the same fields." },
      { h: "2. Matching: scoring fit against the role" },
      { p: "Once a resume is structured, it can be compared to what the role actually needs. A match score is only as good as its reasons: a number with no explanation is a guess you can't audit. The score should tell you which requirements a candidate meets, which they don't, and where the evidence came from." },
      { h: "3. Ranking: a shortlist, not a verdict" },
      { p: "Ranking orders applicants so you start reading from the top instead of the pile. That's where the AI's job ends. It surfaces the strongest fits and the reasons; a person decides who to talk to. Treat the score as a first pass that saves you the first hour, never as the hire/no-hire call." },
      { h: "Where it doesn't help" },
      { ul: ["Judging culture add, motivation or trajectory — that's an interview's job.", "Rescuing a vague role: garbage requirements in, garbage ranking out.", "Replacing your judgment. The goal is a shorter reading list, not fewer decisions."] },
      { p: "Used this way, screening turns a two-week shortlist into an afternoon without pretending to know things it can't. Start from a ranked shortlist with reasons — then do the human part." },
    ],
  },
  {
    slug: "bias-in-hiring-ai",
    title: "Bias in hiring AI: what to check before you trust a score",
    category: "ai-hiring",
    excerpt: "AI can reduce bias or quietly amplify it. A short checklist for keeping screening fair and defensible.",
    author: { name: "Daniel Teoh", role: "Responsible AI Lead" },
    date: "2026-06-10",
    readMins: 6,
    tags: ["Fairness", "Compliance", "AI screening"],
    body: [
      { p: "Automating screening doesn't automatically make it fairer. It can — by applying the same criteria to every applicant instead of a tired recruiter's attention — or it can scale a bad pattern to thousands of candidates at once. The difference is what you check." },
      { h: "Score on skills, not proxies" },
      { p: "A defensible score maps to the requirements of the role: skills, experience, evidence. The moment a model leans on a name, a school, a photo or a postcode as a shortcut for quality, it's learning bias, not fit. Ask what a score is actually built from." },
      { h: "Keep the reasons visible" },
      { p: "If you can't see why a candidate ranked where they did, you can't defend the decision — to a hiring manager, a candidate, or a regulator. Reasons make a score reviewable. No reasons, no trust." },
      { h: "A quick pre-flight checklist" },
      { ul: ["Does the score explain itself with role-relevant reasons?", "Are protected attributes (and their proxies) excluded from scoring?", "Can a human override the ranking, and is that logged?", "Is your data ever used to train shared models? (It shouldn't be.)"] },
      { p: "None of this is exotic. It's the same standard you'd hold a human screener to — written down, applied consistently, and open to review." },
    ],
  },
  {
    slug: "cut-time-to-hire",
    title: "How to cut time-to-hire without lowering the bar",
    category: "recruiting-ops",
    excerpt: "Most delay isn't in the interviews — it's in the gaps between them. Here's where the days actually go.",
    author: { name: "Siti Rahman", role: "Talent Operations" },
    date: "2026-05-28",
    readMins: 6,
    tags: ["Time to hire", "Pipeline", "Automation"],
    body: [
      { p: "When teams try to hire faster, they usually squeeze the interviews — shorter loops, fewer people. That trades quality for speed. But most of the calendar isn't spent interviewing; it's spent waiting. Fix the gaps and you get speed for free." },
      { h: "Find the waiting, not the working" },
      { p: "Map a recent hire day by day. You'll usually find the time isn't in the screen or the panel — it's in the days a resume sat unread, the back-and-forth to book a slot, and the silence while everyone waited for someone to decide. That's where to aim." },
      { h: "Three gaps worth closing" },
      { ul: ["Unread applications: screen on arrival so a shortlist exists the day the role opens.", "Scheduling ping-pong: send one link and let candidates self-book; the invite creates itself.", "Decision drift: one shared scorecard so the panel converges instead of scheduling another chat."] },
      { h: "Speed as a byproduct of a good process" },
      { p: "None of these lower the bar — they remove the dead air around it. Screen early, schedule without friction, decide with a scorecard, and two weeks turns into a few days while the standard stays exactly where you set it." },
    ],
  },
  {
    slug: "building-a-talent-pipeline",
    title: "Building a talent pipeline that actually gets used",
    category: "recruiting-ops",
    excerpt: "Most talent pools are graveyards. What separates a pipeline you search from a spreadsheet you forget.",
    author: { name: "Amira Hassan", role: "Head of Product" },
    date: "2026-05-14",
    readMins: 5,
    tags: ["Talent CRM", "Sourcing", "Pipeline"],
    body: [
      { p: "Every team has a folder of \"great candidates for later.\" Almost no one opens it. The strong runner-up from six months ago is exactly who you need for the role that just opened — but only if you can find them in seconds, not remember they exist." },
      { h: "A pipeline is a search, not a list" },
      { p: "A list you scroll is a list you ignore. A pipeline you can query by skill, role or industry is one you actually reach into. The test is simple: when a role opens, can you surface the five best past applicants before you write the job post?" },
      { h: "Keep it clean, keep it one record per person" },
      { p: "Pipelines rot from duplicates and stale context. Deduplicate so one person is one record even across old and new CVs, keep the notes attached, and tag people while the context is fresh — not a year later when you've forgotten why they were promising." },
      { p: "Do that and \"we'll keep you in mind\" stops being a polite lie. Your next hire is usually already in your database, one search away." },
    ],
  },
  {
    slug: "structured-interviews-guide",
    title: "The case for structured interviews (with a scorecard to steal)",
    category: "interviewing",
    excerpt: "Unstructured interviews mostly measure rapport. Structure is how you measure the job — and compare fairly.",
    author: { name: "Daniel Teoh", role: "Responsible AI Lead" },
    date: "2026-04-30",
    readMins: 8,
    tags: ["Structured interviews", "Scorecards", "Hiring quality"],
    body: [
      { p: "The unstructured interview — a friendly chat, questions made up on the spot — is one of the weakest predictors of job performance we keep using. It mostly measures how much the interviewer liked the candidate. Structure fixes that, and it isn't complicated." },
      { h: "What \"structured\" actually means" },
      { ul: ["The same core questions for every candidate for a role.", "Questions tied to the skills the job needs, not trivia.", "A scorecard with defined criteria, filled in independently before the panel debates."] },
      { h: "Why it works" },
      { p: "Asking everyone the same job-relevant questions makes candidates comparable. Scoring independently before you discuss stops the loudest voice — or the first impression — from anchoring the room. You end up debating evidence instead of vibes." },
      { h: "A scorecard you can copy" },
      { p: "Rate each candidate 1–4 on: role-specific skill, problem-solving, communication, and collaboration. Add one line of evidence per rating. Sum the panel, but read the evidence — a split score is a signal to dig, not average away." },
      { p: "Structure won't make hiring robotic. It makes it fair, comparable and defensible — and it frees the conversation to go deep, because you already know which ground every candidate has to cover." },
    ],
  },
  {
    slug: "interview-questions-that-reveal-skill",
    title: "12 interview questions that reveal real skill",
    category: "interviewing",
    excerpt: "Skip the brainteasers. These behavioral prompts surface how someone actually works.",
    author: { name: "Siti Rahman", role: "Talent Operations" },
    date: "2026-04-16",
    readMins: 5,
    tags: ["Interview questions", "Behavioral", "Screening"],
    body: [
      { p: "The best interview questions aren't clever — they're specific. They ask for a real example and then follow the thread. Here are twelve prompts that get past the rehearsed answer to how a person actually operates." },
      { h: "On the work itself" },
      { ul: ["Walk me through a project you're proud of — what was your part?", "Tell me about a decision you got wrong. How did you find out?", "What's something you changed your mind about in the last year?", "Describe a time the requirements were unclear. What did you do?"] },
      { h: "On working with others" },
      { ul: ["When did you disagree with a teammate? How did it resolve?", "Who's the best person you've worked with, and what made them good?", "Tell me about feedback that was hard to hear.", "How do you keep people updated when a project slips?"] },
      { h: "On depth" },
      { ul: ["Teach me something you know well in five minutes.", "What would you have done differently on your last project?", "What's a problem in your field most people get wrong?", "What do you want to be doing that you can't do today?"] },
      { p: "Ask the same set for a role, score the answers on a scorecard, and follow every claim with \"tell me more.\" The specifics are where the signal lives." },
    ],
  },
];

export const GLOSSARY_TERMS = [
  { slug: "applicant-tracking-system", term: "Applicant Tracking System (ATS)", short: "Software that manages job applications through every hiring stage, from applied to hired.", related: ["recruitment-funnel", "resume-parsing", "job-requisition"],
    body: ["An Applicant Tracking System is the pipeline of record for hiring. It collects applications from every source, stores each candidate's history in one place, and moves them through stages — applied, shortlisted, interviewing, offer, hired — so nothing is lost in an inbox.", "A modern ATS also parses resumes into structured data and ranks applicants against the role, so recruiters start from a shortlist instead of a stack."] },
  { slug: "resume-parsing", term: "Resume parsing", short: "Automatically extracting structured fields — skills, experience, education — from a resume document.", related: ["applicant-tracking-system", "screening", "deduplication"],
    body: ["Resume parsing turns an unstructured document into comparable data: skills, job titles, companies, dates and a summary, regardless of the layout the candidate used.", "Reliable parsing is the foundation of screening and search — without it, every applicant has to be read and retyped by hand before they can be compared."] },
  { slug: "candidate-sourcing", term: "Candidate sourcing", short: "Proactively finding and engaging potential candidates rather than waiting for applications.", related: ["talent-pool", "talent-crm", "passive-candidate"],
    body: ["Sourcing is the proactive side of recruiting: searching databases, networks and your own past applicants to find people who fit an open role, then reaching out.", "The highest-return source is often your existing talent pool — people who already applied, were referred, or were uploaded — because they've shown interest and their data is already on hand."] },
  { slug: "talent-pool", term: "Talent pool", short: "A searchable database of candidates you've collected over time for current and future roles.", related: ["talent-crm", "candidate-sourcing", "deduplication"],
    body: ["A talent pool is every candidate you've ever collected — applicants, referrals, sourced profiles — kept in one searchable place.", "Its value depends entirely on whether you can query it. A pool you can search by skill or role becomes your fastest source of hires; a pool you only scroll is a graveyard."] },
  { slug: "talent-crm", term: "Talent CRM", short: "A candidate relationship system for nurturing and re-engaging people across roles over time.", related: ["talent-pool", "candidate-sourcing", "employer-brand"],
    body: ["A Talent CRM (candidate relationship management) keeps context on the people in your pipeline — notes, tags, past conversations — so relationships continue across roles instead of restarting each time.", "It's what turns a one-time applicant into a candidate you can re-engage the moment a matching role opens."] },
  { slug: "boolean-search", term: "Boolean search", short: "Using operators like AND, OR and NOT to build precise candidate search queries.", related: ["candidate-sourcing", "talent-pool", "screening"],
    body: ["Boolean search combines keywords with logical operators — AND, OR, NOT — and quotation marks to narrow or widen a candidate search precisely.", "It's powerful but brittle: it matches exact strings, so \"JS\" won't find \"JavaScript\" unless you say so. Skill-aware search that understands synonyms is increasingly replacing hand-built Boolean strings."] },
  { slug: "screening", term: "Resume screening", short: "Reviewing applications to decide which candidates advance to interviews.", related: ["applicant-tracking-system", "resume-parsing", "recruitment-funnel"],
    body: ["Screening is the first filter: reading applications against the role's requirements to build a shortlist worth interviewing.", "Done by hand it's the biggest time sink in hiring. Automated screening scores and ranks each applicant so the strongest fits rise to the top — with the reasons — leaving the human decision intact."] },
  { slug: "structured-interview", term: "Structured interview", short: "An interview using the same predefined, job-relevant questions and scoring for every candidate.", related: ["scorecard", "quality-of-hire", "candidate-experience"],
    body: ["A structured interview asks every candidate for a role the same job-relevant questions and scores them against defined criteria.", "It's one of the strongest predictors of job performance because it makes candidates directly comparable and reduces the pull of first impressions and rapport."] },
  { slug: "scorecard", term: "Interview scorecard", short: "A defined set of criteria interviewers rate each candidate against, independently.", related: ["structured-interview", "quality-of-hire"],
    body: ["A scorecard lists the criteria that matter for a role — specific skills, problem-solving, communication — and asks each interviewer to rate the candidate with a line of evidence.", "Filling it in independently before the panel debates keeps one loud voice from anchoring the decision, so the team weighs evidence instead of vibes."] },
  { slug: "time-to-hire", term: "Time to hire", short: "The days between a candidate applying (or being sourced) and accepting an offer.", related: ["time-to-fill", "recruitment-funnel", "offer-acceptance-rate"],
    body: ["Time to hire measures a candidate's journey: from entering your pipeline to accepting an offer. It reflects how efficient your process is for people already in it.", "Most of it is usually waiting — unread applications, scheduling delays, slow decisions — not interviewing, which is where the fastest gains hide."] },
  { slug: "time-to-fill", term: "Time to fill", short: "The days between opening a requisition and a candidate accepting the offer.", related: ["time-to-hire", "job-requisition"],
    body: ["Time to fill measures the role: from the day a job requisition opens to the day someone accepts. It captures sourcing and demand, not just process speed.", "It pairs with time-to-hire — one tells you about the market for the role, the other about the efficiency of your pipeline."] },
  { slug: "quality-of-hire", term: "Quality of hire", short: "A measure of how well new hires perform and stay, tracing hiring decisions to outcomes.", related: ["structured-interview", "scorecard", "cost-per-hire"],
    body: ["Quality of hire links a hiring decision to what happened next: performance, ramp time and retention. It's the metric that actually matters, and the hardest to measure.", "Structured interviews and scorecards improve it by making decisions consistent and evidence-based, which is easier to correlate with outcomes than gut-feel calls."] },
  { slug: "cost-per-hire", term: "Cost per hire", short: "The total cost of filling a role divided by the number of hires.", related: ["time-to-fill", "quality-of-hire", "recruitment-funnel"],
    body: ["Cost per hire sums everything spent to fill roles — advertising, agencies, tools, recruiter time — divided by hires made.", "It's most useful watched over time and alongside quality of hire: the cheapest hire is expensive if it doesn't work out."] },
  { slug: "offer-acceptance-rate", term: "Offer acceptance rate", short: "The share of job offers extended that candidates accept.", related: ["time-to-hire", "candidate-experience", "employer-brand"],
    body: ["Offer acceptance rate is offers accepted divided by offers made. A low rate signals a mismatch — on compensation, timing, or how the process felt.", "A slow or impersonal process is a common, fixable cause: strong candidates take other offers while yours is still deciding."] },
  { slug: "passive-candidate", term: "Passive candidate", short: "Someone not actively job-hunting but open to the right opportunity.", related: ["candidate-sourcing", "talent-crm", "employer-brand"],
    body: ["Passive candidates aren't applying, but they'll move for the right role. They're often the strongest people in a market precisely because they're already employed and doing well.", "Reaching them takes sourcing and a relationship over time — which is what a talent CRM and a credible employer brand are for."] },
  { slug: "employer-brand", term: "Employer brand", short: "How a company is perceived as a place to work by candidates and employees.", related: ["candidate-experience", "offer-acceptance-rate", "passive-candidate"],
    body: ["Employer brand is your reputation as a workplace — what candidates believe about working for you before they ever apply.", "It shows up in application rates, offer acceptance and referrals. Every touchpoint in hiring, from the job post to the rejection email, either builds it or erodes it."] },
  { slug: "candidate-experience", term: "Candidate experience", short: "How applicants perceive your hiring process, from application to decision.", related: ["employer-brand", "offer-acceptance-rate", "recruitment-funnel"],
    body: ["Candidate experience is how it feels to move through your process: how clear the role was, how fast you responded, how respectful the communication.", "It directly affects offer acceptance and employer brand — and even rejected candidates who were treated well become future applicants and referrers."] },
  { slug: "recruitment-funnel", term: "Recruitment funnel", short: "The stages candidates pass through, from applicant to hire, narrowing at each step.", related: ["screening", "time-to-hire", "cost-per-hire"],
    body: ["The recruitment funnel maps how candidates narrow from applied to hired: applied, screened, interviewed, offered, hired.", "Measuring conversion between stages shows where your process leaks — a huge drop after screening means the top of the funnel or the screen itself needs work."] },
  { slug: "job-requisition", term: "Job requisition", short: "The formal request to open and fill a role, often requiring approval.", related: ["applicant-tracking-system", "time-to-fill"],
    body: ["A job requisition is the approved request to hire for a specific role — headcount, budget and the reason attached.", "It's where the funnel begins and where time-to-fill starts counting. Slow approvals here delay everything downstream, before a single candidate is even sourced."] },
  { slug: "deduplication", term: "Candidate deduplication", short: "Merging multiple records of the same person into one, even across old and new applications.", related: ["talent-pool", "resume-parsing", "applicant-tracking-system"],
    body: ["Deduplication ensures one person is one record, even when they've applied twice with different CVs or been sourced and referred separately.", "Without it, talent pools bloat with duplicates, candidates get double-counted, and someone gets two rejection emails for the same role. It's quiet but essential hygiene."] },
];
